version: "3"

networks:
  greenhouse-network:

services:
  plapp-greenhouse-db:
    image: postgres:latest
    container_name: plapp-greenhouse-db
    ports:
      - "5433:5432"
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - greenhouse-network

  plapp-greenhouse-service:
    image: maven:latest
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    ports:
      - "8082:8080"

    command: mvn clean spring-boot:run
    networks:
      - greenhouse-network
volumes:
  database-data:

